### ISSUE TITLE
Ошибка наследования от MyClass(yadm.Document)

### ISSUE THREAD

**Issue by crucl0** [zzzsochi/yadm#3]
``` python
from yadm import Document
from yadm import fields

class ForReference(Document):
    a = fields.StringField()

class Parent(Document):
    a = fields.StringField()
    # b = fields.SetField(())
    # c = fields.ReferenceField(ForReference)
    d = fields.ObjectIdField()
    # e = fields.ListField([])
    d = fields.IntegerField()
    f = fields.FloatField()
    # g = fields.EmbeddedDocumentField(ForReference)
    h = fields.DecimalField()
    i = fields.DatetimeField()
    j = fields.BooleanField()

class Child(Parent):
    pass

#
# Если раскомментировать любое из полей, будет ошибка с одинаковым Traceback:

Traceback (most recent call last):
  File "/home/alekzp/Docs/cod/python/mrtday/taoreg/inherit-fields.py", line 23, in <module>
    class Child(Parent):
  File "/home/alekzp/Docs/cod/python/mrtday/lib/python3.3/site-packages/yadm-0.5-py3.3.egg/yadm/documents.py", line 32, in __init__
    cls_dict[name] = field.copy()
  File "/home/alekzp/Docs/cod/python/mrtday/lib/python3.3/site-packages/yadm-0.5-py3.3.egg/yadm/fields/base.py", line 104, in copy
    return self.__class__(default=self.default)
TypeError: __init__() got an unexpected keyword argument 'default'
```

**Comment by zzzsochi** [comment]
Не актуально.
